Fix build break
Using Ubuntu 18 default gcc cannot make with error:
undefined reference to `get_6bit_ascii' and `get_aligned_size'
Add static symbol to avoid the build error.

And remove -w parameter in README, it cause generate FRU fail.

Signed-off-by: Brian Ma <chma0@nuvoton.com>